services:
  catalogservice:
    image: catalogservice
    container_name: catalog_api
    build:
      context: .
      dockerfile: CatalogService/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
        bash -c "dotnet ef database update --no-build && dotnet CatalogService.dll"
    networks:
      - catalog-network
       
  postgres:
    image: postgres:16-alpine
    container_name: catalog-db
    environment:
      POSTGRES_USER: cataloguser
      POSTGRES_PASSWORD: catalogpassword
      POSTGRES_DB: catalogdb
    expose:
      - "5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data
    networks:
        - catalog-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cataloguser -d catalogdb" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
      
  deliveryservice:
    image: deliveryservice
    container_name: delivery_api
    build:
      context: .
      dockerfile: DeliveryService/Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      postgres-delivery:
        condition: service_healthy
    command: >
        bash -c "dotnet ef database update --no-build && dotnet DeliveryService.dll"
    networks:
      - catalog-network
      
  postgres-delivery:
    image: postgres:16-alpine
    container_name: delivery-db
    environment:
      POSTGRES_USER: deliveryuser
      POSTGRES_PASSWORD: deliverypassword
      POSTGRES_DB: deliverydb
    expose:
      - "5432"
    volumes:
      - delivery_data:/var/lib/postgresql/data
    networks:
      - catalog-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U deliveryuser -d deliverydb" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
      
volumes:
    catalog_data:
    delivery_data:
      
networks:
  catalog-network:
    driver: bridge