services:
  catalogservice:
    image: catalogservice
    container_name: catalog_api
    build:
      context: .
      dockerfile: CatalogService/Dockerfile
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
        bash -c "dotnet ef database update --no-build && dotnet CatalogService.dll"
    networks:
      - catalog-network
       
  postgres:
    image: postgres:16-alpine
    container_name: catalog-db
    environment:
      POSTGRES_USER: cataloguser
      POSTGRES_PASSWORD: catalogpassword
      POSTGRES_DB: catalogdb
    expose:
      - "5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data
    networks:
        - catalog-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cataloguser -d catalogdb" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
      
  deliveryservice:
    image: deliveryservice
    container_name: delivery_api
    build:
      context: .
      dockerfile: DeliveryService/Dockerfile
    expose:
      - "8080"
    depends_on:
      postgres-delivery:
        condition: service_healthy
    command: >
        bash -c "dotnet ef database update --no-build && dotnet DeliveryService.dll"
    networks:
      - catalog-network
      
  postgres-delivery:
    image: postgres:16-alpine
    container_name: delivery-db
    environment:
      POSTGRES_USER: deliveryuser
      POSTGRES_PASSWORD: deliverypassword
      POSTGRES_DB: deliverydb
    expose:
      - "5432"
    volumes:
      - delivery_data:/var/lib/postgresql/data
    networks:
      - catalog-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U deliveryuser -d deliverydb" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
      
  ordersservice:
    image: ordersservice
    container_name: orders_service
    build:
      context: ./OrdersService
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://orders_user:orders_password@postgres-orders:5432/orders_db
      JWT_SECRET: ${IDENTITY_SERVICE_JWT_SECRET}
      RABBITMQ_URL: amqp://admin:admin123@rabbitmq:5672
      CATALOG_SERVICE_URL: http://catalogservice:8080
    expose:
      - "3001"
    depends_on:
      postgres-orders:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - catalog-network
    restart: unless-stopped
      
  postgres-orders:
    image: postgres:16-alpine
    container_name: orders-db
    environment:
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_password
      POSTGRES_DB: orders_db
    expose:
      - "5432"
    volumes:
      - orders_data:/var/lib/postgresql/data
    networks:
      - catalog-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orders_user -d orders_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  identity-db:
    image: postgres:15
    container_name: identity-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: identity_db
    volumes:
      - identity-db-data:/var/lib/postgresql/data
    networks:
      - catalog-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d identity_db" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    networks:
      - catalog-network
    restart: always

  identity-service:
    build: ./identity-service/
    expose:
      - "${IDENTITY_SERVICE_PORT}"
    environment:
      PORT: ${IDENTITY_SERVICE_PORT}
      JWT_SECRET: ${IDENTITY_SERVICE_JWT_SECRET}
      DB_HOST: ${IDENTITY_SERVICE_DB_HOST}
      DB_PORT: ${IDENTITY_SERVICE_DB_PORT}
      DB_USER: ${IDENTITY_SERVICE_DB_USER}
      DB_PASSWORD: ${IDENTITY_SERVICE_DB_PASSWORD}
      DB_NAME: ${IDENTITY_SERVICE_DB_NAME}
    depends_on:
      identity-db:
        condition: service_healthy
    networks:
      - catalog-network
    restart: always

  paymentservice:
    image: paymentservice
    container_name: payment_service
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3002
      DATABASE_URL: postgresql://payment_user:payment_password@postgres-payment:5432/payment_db
      JWT_SECRET: ${IDENTITY_SERVICE_JWT_SECRET}
      RABBITMQ_URL: amqp://admin:admin123@rabbitmq:5672
    expose:
      - "3002"
    depends_on:
      postgres-payment:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - catalog-network
    restart: unless-stopped

  postgres-payment:
    image: postgres:16-alpine
    container_name: payment-db
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_password
      POSTGRES_DB: payment_db
    expose:
      - "5432"
    volumes:
      - payment_data:/var/lib/postgresql/data
    networks:
      - catalog-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U payment_user -d payment_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  restaurantservice:
    image: restaurantservice
    container_name: restaurant_service
    build:
      context: ./RestaurantService
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3003
      MONGODB_URI: mongodb://mongodb:27017/restaurant_db
    expose:
      - "3003"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - catalog-network
    restart: unless-stopped

  notificationservice:
    image: notificationservice
    container_name: notification_service
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3004
      MONGODB_URI: mongodb://mongodb-notifications:27017/notification_db
    expose:
      - "3004"
    depends_on:
      mongodb-notifications:
        condition: service_healthy
    networks:
      - catalog-network
    restart: unless-stopped

  mongodb:
    image: mongo:7-jammy
    container_name: restaurant-mongodb
    environment:
      MONGO_INITDB_DATABASE: restaurant_db
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - catalog-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  mongodb-notifications:
    image: mongo:7-jammy
    container_name: notification-mongodb
    environment:
      MONGO_INITDB_DATABASE: notification_db
    expose:
      - "27017"
    volumes:
      - mongodb_notifications_data:/data/db
    networks:
      - catalog-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8088:80"
    volumes:
      - ./ApiGateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - catalogservice
      - deliveryservice
      - ordersservice
      - identity-service
      - paymentservice
      - restaurantservice
      - notificationservice
    networks:
      - catalog-network
    restart: unless-stopped

  frontend:
    image: frontend
    container_name: frontend_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:3000"
    depends_on:
      - api-gateway
    networks:
      - catalog-network
    restart: unless-stopped

  rabbitmq:
      image: rabbitmq:management-alpine
      container_name: rabbitmq
      ports:
        - "5672:5672"     # RabbitMQ main port
        - "15672:15672"   # Management UI
      environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin123
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq
      networks:
        - catalog-network
      healthcheck:
        test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
        interval: 10s
        timeout: 5s
        retries: 5
      restart: unless-stopped
      
volumes:
    catalog_data:
    delivery_data:
    orders_data:
    identity-db-data:
    payment_data:
    mongodb_data:
    mongodb_notifications_data:
    rabbitmq_data:

networks:
  catalog-network:
    driver: bridge