services:
  catalogservice:
    image: catalogservice
    container_name: catalog_api
    build:
      context: .
      dockerfile: CatalogService/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
        bash -c "dotnet ef database update --no-build && dotnet CatalogService.dll"
    networks:
      - catalog-network
       
  postgres:
    image: postgres:16-alpine
    container_name: catalog-db
    environment:
      POSTGRES_USER: cataloguser
      POSTGRES_PASSWORD: catalogpassword
      POSTGRES_DB: catalogdb
    expose:
      - "5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data
    networks:
        - catalog-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cataloguser -d catalogdb" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
      
  deliveryservice:
    image: deliveryservice
    container_name: delivery_api
    build:
      context: .
      dockerfile: DeliveryService/Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      postgres-delivery:
        condition: service_healthy
    command: >
        bash -c "dotnet ef database update --no-build && dotnet DeliveryService.dll"
    networks:
      - catalog-network
      
  postgres-delivery:
    image: postgres:16-alpine
    container_name: delivery-db
    environment:
      POSTGRES_USER: deliveryuser
      POSTGRES_PASSWORD: deliverypassword
      POSTGRES_DB: deliverydb
    expose:
      - "5432"
    volumes:
      - delivery_data:/var/lib/postgresql/data
    networks:
      - catalog-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U deliveryuser -d deliverydb" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
      
  ordersservice:
    image: ordersservice
    container_name: orders_service
    build:
      context: ./OrdersService
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://orders_user:orders_password@postgres-orders:5432/orders_db
    ports:
      - "3001:3001"
    depends_on:
      postgres-orders:
        condition: service_healthy
    networks:
      - catalog-network
    restart: unless-stopped
      
  postgres-orders:
    image: postgres:16-alpine
    container_name: orders-db
    environment:
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_password
      POSTGRES_DB: orders_db
    expose:
      - "5432"
    volumes:
      - orders_data:/var/lib/postgresql/data
    networks:
      - catalog-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orders_user -d orders_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  identity-db:
    image: postgres:15
    container_name: identity-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: identity_db
    volumes:
      - identity-db-data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    restart: always

  identity-service:
    build: ./identity-service/
    ports:
      - "${IDENTITY_SERVICE_PORT}:${IDENTITY_SERVICE_PORT}"
    environment:
      PORT: ${IDENTITY_SERVICE_PORT}
      JWT_SECRET: ${IDENTITY_SERVICE_JWT_SECRET}
      DB_HOST: ${IDENTITY_SERVICE_DB_HOST}
      DB_PORT: ${IDENTITY_SERVICE_DB_PORT}
      DB_USER: ${IDENTITY_SERVICE_DB_USER}
      DB_PASSWORD: ${IDENTITY_SERVICE_DB_PASSWORD}
      DB_NAME: ${IDENTITY_SERVICE_DB_NAME}
    depends_on:
      - identity-db
    restart: always
    
volumes:
    catalog_data:
    delivery_data:
    orders_data:
    identity-db-data:

networks:
  catalog-network:
    driver: bridge